name: custom-checkout
author: Your Name <your.email@example.com>
description: A Buildkite plugin to allow custom repository checkout.
version: "1.0.0"

configuration:
  repository:
    type: string
    required: true
    description: "The Git repository URL to clone."
  branch:
    type: string
    required: false
    description: "The Git branch to checkout."
  commit:
    type: string
    required: false
    description: "The Git commit SHA to checkout."
